use crate::diff::engine::DiffLine;
use crate::fs::write_atomically;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use tauri::{AppHandle, Manager};

/// Mirrors the frontend's `ImageAttachment` (`$lib/images.ts`) — a persisted chat turn keeps an
/// attached image's mime type alongside its base64 data so it can be redisplayed as a thumbnail
/// after reloading, without re-deriving the mime type from a file path that may no longer exist.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatImageAttachment {
    pub base64: String,
    pub mime_type: String,
}

/// A file this turn considered "in scope" (the active document, auto-included, plus any extra
/// files explicitly attached) — the full content is kept here even for turns that skipped
/// resending it to Ollama because it hadn't changed since it was last sent, so the frontend can
/// keep comparing against it as the source of truth for that de-duplication (`conversation.svelte.ts`).
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatAttachedFile {
    pub path: String,
    pub content: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct ChatTurn {
    pub id: String,
    /// `"chat"` (plain conversational reply, never touches a document) or `"write"` (produces a
    /// diff against `target_file`, reviewed/applied). Left as a plain string rather than a Rust
    /// enum — this module never branches on it, it's a dumb store; the frontend owns the meaning
    /// of the values it writes here.
    pub mode: String,
    pub model: String,
    pub instruction: String,
    pub images: Vec<ChatImageAttachment>,
    pub attached_files: Vec<ChatAttachedFile>,
    pub thinking_text: String,
    pub answer_length: u32,
    pub status: String,
    pub error_message: Option<String>,
    pub response_text: Option<String>,
    pub target_file: Option<String>,
    pub diff: Option<Vec<DiffLine>>,
    pub pending_text: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Chat {
    pub id: String,
    pub title: String,
    pub created_at: String,
    pub updated_at: String,
    #[serde(default)]
    pub turns: Vec<ChatTurn>,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ChatSummary {
    pub id: String,
    pub title: String,
    pub updated_at: String,
}

#[derive(Debug, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
struct ProjectChatState {
    last_active_chat_id: Option<String>,
}

/// Chats live in the app's global config directory, not inside the project folder — nothing
/// project-visible, nothing to `.gitignore`. A project is identified by a stable hash of its
/// absolute path (`<config-dir>/projects/<hash>/...`); FNV-1a rather than a crate dependency or
/// `std`'s `DefaultHasher` (whose exact algorithm is explicitly *not* guaranteed stable across
/// Rust versions — a real risk for something that has to keep resolving to the same folder for
/// as long as a project exists) — FNV-1a is a fixed, well-known algorithm with no such risk, and
/// this only needs to be a stable, low-collision folder name, not cryptographically secure.
fn stable_hash(input: &str) -> String {
    const FNV_OFFSET_BASIS: u64 = 0xcbf29ce484222325;
    const FNV_PRIME: u64 = 0x100000001b3;
    let mut hash = FNV_OFFSET_BASIS;
    for &byte in input.as_bytes() {
        hash ^= u64::from(byte);
        hash = hash.wrapping_mul(FNV_PRIME);
    }
    format!("{hash:016x}")
}

fn project_dir(base: &Path, project_root: &str) -> PathBuf {
    base.join("projects").join(stable_hash(project_root))
}

fn chats_dir(base: &Path, project_root: &str) -> PathBuf {
    project_dir(base, project_root).join("chats")
}

fn chat_path(base: &Path, project_root: &str, chat_id: &str) -> PathBuf {
    // `chat_id` is always a `crypto.randomUUID()` generated by the frontend, never
    // user-supplied free text, so there's no path-traversal concern in joining it directly.
    chats_dir(base, project_root).join(format!("{chat_id}.json"))
}

fn state_path(base: &Path, project_root: &str) -> PathBuf {
    project_dir(base, project_root).join("state.json")
}

/// Creates the project's storage folder and, the first time it's seen, drops a small
/// `project.json` recording the original path next to the hash — purely for a human (or a future
/// "manage stored projects" feature) browsing the config directory to tell which folder a hash
/// belongs to; nothing in this module ever reads it back.
fn ensure_project_dir(base: &Path, project_root: &str) -> Result<PathBuf, String> {
    let dir = project_dir(base, project_root);
    std::fs::create_dir_all(&dir)
        .map_err(|err| format!("Could not create project storage folder: {err}"))?;
    let meta_path = dir.join("project.json");
    if !meta_path.exists() {
        let raw = serde_json::to_string_pretty(&serde_json::json!({ "path": project_root }))
            .map_err(|err| format!("Could not serialize project metadata: {err}"))?;
        write_atomically(&meta_path, raw.as_bytes())
            .map_err(|err| format!("Could not write project metadata: {err}"))?;
    }
    Ok(dir)
}

fn app_data_base(app: &AppHandle) -> Result<PathBuf, String> {
    app.path()
        .app_config_dir()
        .map_err(|err| format!("Could not resolve config directory: {err}"))
}

fn list_chats_inner(base: &Path, project_root: &str) -> Result<Vec<ChatSummary>, String> {
    let dir = chats_dir(base, project_root);
    if !dir.is_dir() {
        return Ok(Vec::new());
    }

    let entries =
        std::fs::read_dir(&dir).map_err(|err| format!("Could not list chats: {err}"))?;

    let mut summaries = Vec::new();
    for entry in entries {
        let Ok(entry) = entry else { continue };
        let path = entry.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("json") {
            continue;
        }
        // Best-effort, same philosophy as the project file-tree scan: one unreadable/corrupt
        // chat file shouldn't take down the whole switcher list.
        let Ok(raw) = std::fs::read_to_string(&path) else {
            continue;
        };
        let Ok(chat) = serde_json::from_str::<Chat>(&raw) else {
            continue;
        };
        summaries.push(ChatSummary {
            id: chat.id,
            title: chat.title,
            updated_at: chat.updated_at,
        });
    }

    summaries.sort_by(|a, b| b.updated_at.cmp(&a.updated_at));
    Ok(summaries)
}

fn load_chat_inner(base: &Path, project_root: &str, chat_id: &str) -> Result<Chat, String> {
    let path = chat_path(base, project_root, chat_id);
    let raw =
        std::fs::read_to_string(&path).map_err(|err| format!("Could not read chat: {err}"))?;
    serde_json::from_str(&raw).map_err(|err| format!("Could not parse chat: {err}"))
}

fn save_chat_inner(base: &Path, project_root: &str, chat: &Chat) -> Result<(), String> {
    ensure_project_dir(base, project_root)?;
    let dir = chats_dir(base, project_root);
    std::fs::create_dir_all(&dir).map_err(|err| format!("Could not create chats folder: {err}"))?;
    let path = chat_path(base, project_root, &chat.id);
    let raw = serde_json::to_string_pretty(chat)
        .map_err(|err| format!("Could not serialize chat: {err}"))?;
    write_atomically(&path, raw.as_bytes()).map_err(|err| format!("Could not save chat: {err}"))
}

fn delete_chat_inner(base: &Path, project_root: &str, chat_id: &str) -> Result<(), String> {
    let path = chat_path(base, project_root, chat_id);
    if path.exists() {
        std::fs::remove_file(&path).map_err(|err| format!("Could not delete chat: {err}"))?;
    }
    Ok(())
}

fn get_last_active_chat_id_inner(
    base: &Path,
    project_root: &str,
) -> Result<Option<String>, String> {
    let path = state_path(base, project_root);
    if !path.exists() {
        return Ok(None);
    }
    let raw = std::fs::read_to_string(&path)
        .map_err(|err| format!("Could not read project state: {err}"))?;
    // A corrupted state.json just means "no remembered chat" — not worth failing the whole
    // project open over, same reasoning as `settings/store.rs`'s fallback-to-default.
    let state: ProjectChatState = serde_json::from_str(&raw).unwrap_or_default();
    Ok(state.last_active_chat_id)
}

fn set_last_active_chat_id_inner(
    base: &Path,
    project_root: &str,
    chat_id: Option<String>,
) -> Result<(), String> {
    ensure_project_dir(base, project_root)?;
    let state = ProjectChatState {
        last_active_chat_id: chat_id,
    };
    let raw = serde_json::to_string_pretty(&state)
        .map_err(|err| format!("Could not serialize project state: {err}"))?;
    write_atomically(&state_path(base, project_root), raw.as_bytes())
        .map_err(|err| format!("Could not save project state: {err}"))
}

#[tauri::command]
pub fn list_chats(app: AppHandle, project_root: String) -> Result<Vec<ChatSummary>, String> {
    list_chats_inner(&app_data_base(&app)?, &project_root)
}

#[tauri::command]
pub fn load_chat(app: AppHandle, project_root: String, chat_id: String) -> Result<Chat, String> {
    load_chat_inner(&app_data_base(&app)?, &project_root, &chat_id)
}

#[tauri::command]
pub fn save_chat(app: AppHandle, project_root: String, chat: Chat) -> Result<(), String> {
    save_chat_inner(&app_data_base(&app)?, &project_root, &chat)
}

#[tauri::command]
pub fn delete_chat(app: AppHandle, project_root: String, chat_id: String) -> Result<(), String> {
    delete_chat_inner(&app_data_base(&app)?, &project_root, &chat_id)
}

#[tauri::command]
pub fn get_last_active_chat_id(
    app: AppHandle,
    project_root: String,
) -> Result<Option<String>, String> {
    get_last_active_chat_id_inner(&app_data_base(&app)?, &project_root)
}

#[tauri::command]
pub fn set_last_active_chat_id(
    app: AppHandle,
    project_root: String,
    chat_id: Option<String>,
) -> Result<(), String> {
    set_last_active_chat_id_inner(&app_data_base(&app)?, &project_root, chat_id)
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TempBase {
        path: PathBuf,
    }

    impl TempBase {
        fn new(label: &str) -> Self {
            let path = std::env::temp_dir().join(format!(
                "markllama-chat-store-test-{label}-{}",
                std::process::id()
            ));
            let _ = std::fs::remove_dir_all(&path);
            std::fs::create_dir_all(&path).expect("create temp base dir");
            TempBase { path }
        }
    }

    impl Drop for TempBase {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.path);
        }
    }

    const PROJECT_ROOT: &str = "/Users/example/my-project";

    fn sample_chat(id: &str, title: &str) -> Chat {
        Chat {
            id: id.to_string(),
            title: title.to_string(),
            created_at: "2026-01-01T00:00:00Z".to_string(),
            updated_at: "2026-01-01T00:00:00Z".to_string(),
            turns: vec![ChatTurn {
                id: "turn-1".to_string(),
                mode: "chat".to_string(),
                model: "llama3.2".to_string(),
                instruction: "What does this mean?".to_string(),
                images: Vec::new(),
                attached_files: vec![ChatAttachedFile {
                    path: "notes.md".to_string(),
                    content: "# Notes".to_string(),
                }],
                thinking_text: String::new(),
                answer_length: 42,
                status: "done".to_string(),
                error_message: None,
                response_text: Some("It means...".to_string()),
                target_file: None,
                diff: None,
                pending_text: None,
            }],
        }
    }

    #[test]
    fn stable_hash_is_deterministic_and_distinguishes_different_paths() {
        assert_eq!(stable_hash("/a/b"), stable_hash("/a/b"));
        assert_ne!(stable_hash("/a/b"), stable_hash("/a/c"));
    }

    #[test]
    fn list_chats_on_a_project_with_no_chats_yet_is_empty_not_an_error() {
        let base = TempBase::new("empty");
        let result = list_chats_inner(&base.path, PROJECT_ROOT).expect("should succeed");
        assert!(result.is_empty());
    }

    #[test]
    fn save_then_load_round_trips_a_chat_exactly() {
        let base = TempBase::new("roundtrip");
        let chat = sample_chat("chat-1", "What does this mean?");
        save_chat_inner(&base.path, PROJECT_ROOT, &chat).expect("save should succeed");

        let loaded =
            load_chat_inner(&base.path, PROJECT_ROOT, "chat-1").expect("load should succeed");
        assert_eq!(loaded.title, "What does this mean?");
        assert_eq!(loaded.turns.len(), 1);
        assert_eq!(loaded.turns[0].response_text, Some("It means...".to_string()));
        assert_eq!(loaded.turns[0].attached_files[0].path, "notes.md");
        assert_eq!(loaded.turns[0].attached_files[0].content, "# Notes");
    }

    #[test]
    fn saving_a_chat_writes_project_metadata_alongside_it() {
        let base = TempBase::new("metadata");
        save_chat_inner(&base.path, PROJECT_ROOT, &sample_chat("chat-1", "Hi")).unwrap();

        let meta_path = project_dir(&base.path, PROJECT_ROOT).join("project.json");
        let raw = std::fs::read_to_string(&meta_path).expect("project.json should exist");
        let meta: serde_json::Value = serde_json::from_str(&raw).unwrap();
        assert_eq!(meta["path"], PROJECT_ROOT);
    }

    #[test]
    fn different_projects_never_share_a_storage_folder() {
        let base = TempBase::new("isolation");
        save_chat_inner(&base.path, "/Users/example/project-a", &sample_chat("chat-1", "A"))
            .unwrap();
        save_chat_inner(&base.path, "/Users/example/project-b", &sample_chat("chat-1", "B"))
            .unwrap();

        let a = list_chats_inner(&base.path, "/Users/example/project-a").unwrap();
        let b = list_chats_inner(&base.path, "/Users/example/project-b").unwrap();
        assert_eq!(a.len(), 1);
        assert_eq!(b.len(), 1);
        assert_eq!(a[0].title, "A");
        assert_eq!(b[0].title, "B");
    }

    #[test]
    fn list_chats_returns_saved_chats_sorted_newest_first() {
        let base = TempBase::new("sorted");
        let mut older = sample_chat("chat-old", "Older");
        older.updated_at = "2026-01-01T00:00:00Z".to_string();
        let mut newer = sample_chat("chat-new", "Newer");
        newer.updated_at = "2026-01-02T00:00:00Z".to_string();

        save_chat_inner(&base.path, PROJECT_ROOT, &older).unwrap();
        save_chat_inner(&base.path, PROJECT_ROOT, &newer).unwrap();

        let summaries = list_chats_inner(&base.path, PROJECT_ROOT).expect("should succeed");
        assert_eq!(summaries.len(), 2);
        assert_eq!(summaries[0].id, "chat-new");
        assert_eq!(summaries[1].id, "chat-old");
    }

    #[test]
    fn delete_chat_removes_it_from_the_list() {
        let base = TempBase::new("delete");
        save_chat_inner(&base.path, PROJECT_ROOT, &sample_chat("chat-1", "Doomed")).unwrap();
        assert_eq!(list_chats_inner(&base.path, PROJECT_ROOT).unwrap().len(), 1);

        delete_chat_inner(&base.path, PROJECT_ROOT, "chat-1").expect("delete should succeed");
        assert!(list_chats_inner(&base.path, PROJECT_ROOT).unwrap().is_empty());
    }

    #[test]
    fn delete_chat_on_a_missing_chat_is_not_an_error() {
        let base = TempBase::new("delete-missing");
        assert!(delete_chat_inner(&base.path, PROJECT_ROOT, "does-not-exist").is_ok());
    }

    #[test]
    fn last_active_chat_id_round_trips_through_project_state() {
        let base = TempBase::new("last-active");
        assert_eq!(get_last_active_chat_id_inner(&base.path, PROJECT_ROOT).unwrap(), None);

        set_last_active_chat_id_inner(&base.path, PROJECT_ROOT, Some("chat-1".to_string()))
            .unwrap();
        assert_eq!(
            get_last_active_chat_id_inner(&base.path, PROJECT_ROOT).unwrap(),
            Some("chat-1".to_string())
        );

        set_last_active_chat_id_inner(&base.path, PROJECT_ROOT, None).unwrap();
        assert_eq!(get_last_active_chat_id_inner(&base.path, PROJECT_ROOT).unwrap(), None);
    }
}
